### ISSUE TITLE
Text reducer mistaking strings for integers?

### ISSUE THREAD

**Issue by jschell42** [zooniverse/aggregation-for-caesar#297] opened 2020-04-29 12:08 UTC
We're using the text reducer on the MI-Bug project and ran into some issues trying to reduce the text classifications for the geographic entries on the specimen labels. However, the program failed to complete when it ran into entries it thought were integers instead of strings. We realized that if a volunteer had put in something that resembles an arithmetic operation (10-12 km NE, for instance), the program would try to resolve that "10-12" to -2 and then fail. We ended up enclosing all the text classifications in "!" which allowed the program to complete, then we removed them afterwards. Not sure if this is something that could be addressed in the reducer itself, but wanted to bring it to your attention.

**Comment by CKrawczyk** [comment] 2020-04-29 12:44
What version of the aggregation code are you using?

This should have been addressed in #272 and that and that is included in version 3.4.2 and up.  If you are using the latest version that means my fix will have to be moved to the extractor level rather than the reducer level.  Although this might be happening when the csv is read in, so before it even reaches the extractor...

**Comment by jschell42** [comment] 2020-04-29 13:10
3.4.3.

**Comment by CKrawczyk** [comment] 2020-04-29 13:48
I have identified the cause of the issue in #298 I need to do a bit more testing before creating a new release.

**Comment by jschell42** [comment] 2020-04-29 13:54
Ok, sounds good. For now we'll just use the [!] method. Thanks for checking into this!

**Closed** 2020-04-30 10:34 UTC

**Comment by CKrawczyk** [comment] 2020-04-30 10:48
The fix has been merged with master if you want to install the latest version directly from github.  I will release a new version on pip in the coming weeks, I want to fix a few more bugs before pushing to pip.

**Comment by jschell42** [comment] 2020-04-30 13:03
Thanks! Just tested it from Github and it works great now.
